#!/usr/bin/env/groovy

@Library('jenkins-shared-library')
def gv 

pipeline {
    agent any
    tools {
        maven 'maven-3.99'
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('init build') {
            steps {
                script {
                    gv = load "jenkins/scripts/script.groovy"
                }
            }
        }
        stage('Build') {
            steps {
                script {
                 buildApp()
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    testApp()
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage( 'Build image'){
            steps {
                script {
                    buildAndPushDockerImage()
                }
            }
        }
        
        stage('Deliver') { 
            steps {
                script {
                    gv.deliverApp()    
                }      
            }
        }
    }
}
